site.collections.digest-posts.from-data.id-key=_key
site.collections.digest-posts.layout=digest-post
site.collections.digest-swipe.from-data.id-key=_key
site.collections.digest-swipe.from-data.name=digest-posts
site.collections.digest-swipe.layout=digest-swipe
quarkus.web-bundler.bundling.external=/images/*
%dev.quarkus.http.host=0.0.0.0
